# Configuration flags for the project
SIGLIP_ENABLED = True
DINO_ENABLED = False
E5_ENABLED = True
BM25_ENABLED = True

VECTOR_STORE = "FAISS"  # options: FAISS, QDRANT, MILVUS
OCR_BACKEND = "PP_OCR"  # fallback: EasyOCR
ENABLE_LLM_EXPANSION = False
ENABLE_LLM_ANSWERING = True
CAPTION_ENABLED = False

# QA context window (ms)
QA_CONTEXT_BEFORE_MS = 5000
QA_CONTEXT_AFTER_MS = 5000

# TRAKE settings
TRAKE_CANDIDATE_VIDEOS = 10
TRAKE_BEAM_WIDTH = 30